# Generated by Django 3.2.13 on 2022-06-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipcode', models.CharField(max_length=7)),
                ('sido', models.CharField(max_length=7)),
                ('gugun', models.CharField(max_length=30, null=True)),
                ('dong', models.CharField(max_length=50)),
                ('ri', models.CharField(max_length=100, null=True)),
                ('bunji', models.CharField(max_length=40, null=True)),
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zipcode',
            },
        ),
    ]
