# Generated by Django 3.2.13 on 2022-06-29 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_alter_member_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='addr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='member',
            name='passwd',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='join.zipcode'),
        ),
    ]
