# Generated by Django 3.2.13 on 2022-06-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_auto_20220629_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
