# Generated by Django 3.2.13 on 2022-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_auto_20220629_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='userid',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
