# Generated by Django 3.2.13 on 2022-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pds',
            name='fdowns',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pds',
            name='fsizes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
