# Generated by Django 3.2.13 on 2022-07-05 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0008_alter_member_userid'),
        ('board', '0002_alter_board_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cno', models.IntegerField()),
                ('comments', models.TextField()),
                ('regdate', models.DateTimeField(default=datetime.datetime.now)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='join.member')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['cno'],
            },
        ),
    ]
